version: '3.9'

services:
  tracking-bp-api:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/src/config/firebase-service-account-key.json"
    env_file:
      - .env