version: '3.9'

services:
  bettion-healtcare-api:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/src/config/tracking-blood-pressure-fa7d5b0b3e2a.json"
    env_file:
      - .env